# Generated by Django 5.2.4 on 2025-08-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_street', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
